=== xkolm036/znackovaci_jazyky/game.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="game">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="author" type="xs:string" />
              <xs:element name="ReleseDate" type="xs:date"/>
              <xs:element name="language" type="lang" default= "EN-US"/>
              <xs:element name="subtitles">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="prepinac">
                      <xs:attribute name="lang" type="lang" default="EN-US" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="enable-sound" type="prepinac" default="Enabled"/>
              <xs:element name="difficult" type="difficult"/>
              <xs:element name="tutorial" type="prepinac"/>
              <xs:element name="autosave" type="prepinac" default="Enabled"/>
            </xs:sequence>
            <xs:attribute name="version" type="xs:string" fixed="1.02 (222AXH)" />
          </xs:complexType>
        </xs:element>
        <xs:element name="display">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="display-mode" type="dmode" />
              <xs:element name="resolution" type="resolution" />
              <xs:element name="refresh-rate" type="refresh" default="60 Hz" />
              <xs:element name="aspect-ratio" type="aspect" />
              <xs:element name="monitor" type="xs:string" default="Primary"/>
              <xs:element name="anti-aliasing" type="aliasing" />
              <xs:element name="gama" type="Null-To-100" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="graphics">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="textures">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="resolution" type="nastaveni-urovne" />
                    <xs:element name="filtering" type="filtering" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="environment">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="view-distance" type="Null-To-10"/>
                    <xs:element name="environment-detail" type="Null-To-10" />
                    <xs:element name="ground-clutter" type="Null-To-10" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="effects">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="depth-effects" type="nastaveni-urovne" />
                    <xs:element name="shadow-quality" type="nastaveni-urovne" />
                    <xs:element name="water-quality" type="nastaveni-urovne" />
                    <xs:element name="weather-quality" type="nastaveni-urovne" />
                    <xs:element name="grass-quality" type="nastaveni-urovne" />
                    <xs:element name="reflection-quality" type="nastaveni-urovne" />
                    <xs:element name="SSAO" type="nastaveni-urovne" />
                    <xs:element name="Graphic-API" type="direct" default="DirectX 9" />
                    <xs:element name="post-procces-aa" type="post-procces" />
                    <xs:element name="motion_blur" type="prepinac" />
                    <xs:element name="Tesselation" type="nastaveni-urovne" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="profile" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="sound">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Hardware">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="sound-channels" type="soundchannels" />
                    <xs:element name="sound-cache" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="sound-output" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="Volume">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="menu-music" type="Null-To-100" />
                    <xs:element name="sound" type="Null-To-100" />
                    <xs:element name="music" type="Null-To-100" />
                    <xs:element name="ambience" type="Null-To-100" />
                    <xs:element name="dialog" type="Null-To-100" />
                    <xs:element name="voicechat">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="volume" type="xs:unsignedByte" />
                          <xs:element name="mode" type="voicemode" />
                          <xs:element name="microphone_sensitivity" type="Null-To-100" />
                          <xs:element name="microphone_volume" type="Null-To-100" />
                        </xs:sequence>
                        <xs:attribute name="enabled" type="prepinac" use="required" />
                        <xs:attribute name="input-device" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="master-volume" type="Null-To-100" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="multiplayer">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="server" type="xs:string" />
              <xs:element name="maxping" type="xs:unsignedByte" />
            </xs:sequence>
            <xs:attribute name="port" type="xs:unsignedShort" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="profile">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="firtname" type="xs:string" />
              <xs:element name="lastname" type="xs:string" />
              <xs:element name="gender" type="xs:string" />
              <xs:element name="age" type="xs:unsignedInt" />
              <xs:element name="nationality" type="xs:string" />
              <xs:element name="email" type="email" />
            </xs:sequence>
            <xs:attribute name="nickname" type="nickname" default="Player" />
          </xs:complexType>
        </xs:element>
        <xs:element name="controls">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="input" type="control" />
              <xs:element name="mouse-sensitivity" type="Null-To-100" />
              <xs:element name="inverted_mouse">
                <xs:complexType>
                  <xs:attribute name="horizontal" type="prepinac" default="Disabled" />
                  <xs:attribute name="vertical" type="prepinac" default="Disabled" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Omezení-->
  <xs:simpleType name="prepinac">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Enabled"/>
      <xs:enumeration value="Disabled"/>
    </xs:restriction>
  </xs:simpleType>
  
<!--Jazykove omezeni-->
  <xs:simpleType name="lang">
    <xs:restriction base="xs:string">
      <xs:enumeration value="EN-US"/>
      <xs:enumeration value="EN-GB"/>
      <xs:enumeration value="RU"/>
      <xs:enumeration value="GR"/>
      <xs:enumeration value="CZ"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Volba hodnot 0-10-->
  <xs:simpleType name="Null-To-10">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Volba hodnot 0-100-->
  <xs:simpleType name="Null-To-100">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Urovně v nastaveni-->
  <xs:simpleType name="nastaveni-urovne">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Low"/>
      <xs:enumeration value="Good"/>
      <xs:enumeration value="High"/>
      <xs:enumeration value="Ultra"/>
    </xs:restriction>
  </xs:simpleType>
  
<!--Hodnoty post-proccesu-->
  <xs:simpleType name="post-procces">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None"/>
      <xs:enumeration value="FXAA Low"/>
      <xs:enumeration value="FXAA High"/>
      <xs:enumeration value="CMAA"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Hodnoty directX-->
  <xs:simpleType name="direct">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DirectX 9"/>
      <xs:enumeration value="DirectX 11"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Hodnoty obtížnosti-->
  <xs:simpleType name="difficult">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Easy"/>
      <xs:enumeration value="Medium"/>
      <xs:enumeration value="Hard"/>
      <xs:enumeration value="Very Hard"/>
    </xs:restriction>
  </xs:simpleType>
  
<!--Rozlišení-->
  <xs:simpleType name="resolution">
    <xs:restriction base="xs:string">
      <xs:enumeration value="1920 X 1200"/>
      <xs:enumeration value="1920 X 1080"/>
      <xs:enumeration value="1680 X 1050"/>
      <xs:enumeration value="1600 X 1200"/>
      <xs:enumeration value="1400 X 1050"/>
      <xs:enumeration value="1366 X 768"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Zobrazení-->
  <xs:simpleType name="dmode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Fullscreen"/>
      <xs:enumeration value="Windowed(Fullscreen)"/>
      <xs:enumeration value="Windowed"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Frekvence monitoru-->
  <xs:simpleType name="refresh">
    <xs:restriction base="xs:string">
      <xs:enumeration value="120 Hz"/>
      <xs:enumeration value="60 Hz"/>
      <xs:enumeration value="50 Hz"/>  
    </xs:restriction>
  </xs:simpleType>
  
  <!--Poměr stran monitoru-->
  <xs:simpleType name="aspect">
    <xs:restriction base="xs:string">
      <xs:enumeration value="16:9"/>
      <xs:enumeration value="4:3"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Hodnoty alliasingu-->
  <xs:simpleType name="aliasing">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none"/>
      <xs:enumeration value="FXAA Low"/>
      <xs:enumeration value="FXAA High"/>
      <xs:enumeration value="CMAA"/>
      <xs:enumeration value="MSAA 2x"/>
      <xs:enumeration value="MSAA 4x"/>
      <xs:enumeration value="MSAA 8x"/>
      <xs:enumeration value="SSAA 4x"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Poměr stran monitoru-->
  <xs:simpleType name="control">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Mouse and keyboard"/>
      <xs:enumeration value="Gamepad"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- Omezení nastavení emailových adres -->
  <xs:simpleType name="email">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^@]+@[^\.]+\..+"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!--Nickname-->
  <xs:simpleType name="nickname">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Filtering-->
  <xs:simpleType name="filtering">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Bilinear"/>
      <xs:enumeration value="Trilinear"/>
      <xs:enumeration value="2x Anisotropic"/>
      <xs:enumeration value="4x Anisotropic"/>
      <xs:enumeration value="8x Anisotropic"/>
      <xs:enumeration value="16x Anisotropic"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Sound Chanels-->
  <xs:simpleType name="soundchannels">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Low(24)"/>
      <xs:enumeration value="Medium(48)"/>
      <xs:enumeration value="High(64)"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Voicemode-->
  <xs:simpleType name="voicemode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Voice detection"/>
      <xs:enumeration value="Push-To-Talk"/>
      <xs:enumeration value="Countinuous Transmission"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== xkolm036/znackovaci_jazyky/game.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="game.xsl"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="game.xsd">

  <!--Obecné nastavení-->
  <game version="1.02 (222AXH)">
    <author>Blizzard</author>
    <ReleseDate>2015-07-01</ReleseDate>
    <language>EN-US</language>
    <subtitles lang="CZ">Enabled</subtitles>
    <enable-sound>Enabled</enable-sound>
    <difficult>Easy</difficult>
    <tutorial>Enabled</tutorial>
    <autosave></autosave>
  </game>
  <!--Nastaveni obrazovky-->
  <display>
    <display-mode>Fullscreen</display-mode>
    <resolution>1920 X 1200</resolution>
    <refresh-rate>60 Hz</refresh-rate>
    <aspect-ratio>16:9</aspect-ratio>
    <monitor>Primary</monitor>
    <anti-aliasing>SSAA 4x</anti-aliasing>
    <gama>50</gama>
  </display>
  <!--Grafické nastavení-->
  <graphics profile="Custom">
    <textures>
      <resolution>High</resolution>
      <filtering>2x Anisotropic</filtering>
    </textures>
    <environment>
      <view-distance>9</view-distance>
      <environment-detail>5</environment-detail>
      <ground-clutter>6</ground-clutter>
    </environment>
    <effects>
      <depth-effects>Good</depth-effects>
      <shadow-quality>Good</shadow-quality>
      <water-quality>Ultra</water-quality>
      <weather-quality>High</weather-quality>
      <grass-quality>Low</grass-quality>
      <reflection-quality>High</reflection-quality>
      <SSAO>Low</SSAO>
      <Graphic-API>DirectX 11</Graphic-API>
      <post-procces-aa>FXAA Low</post-procces-aa>
      <motion_blur>Enabled</motion_blur>
      <Tesselation>Good</Tesselation>
    </effects>
  </graphics>
  <!--Nastavení zvuku-->
  <sound>
    <Hardware sound-output="System default">
      <sound-channels>High(64)</sound-channels>
      <sound-cache>Large(64MB)</sound-cache>
    </Hardware>
    <Volume master-volume="50">
      <menu-music>50</menu-music>
      <sound>100</sound> <!--Test-->
      <music>45</music>
      <ambience>50</ambience>
      <dialog>35</dialog>
      <voicechat enabled="Enabled" input-device="system default">
        <volume>33</volume>
        <mode>Push-To-Talk</mode>
        <microphone_sensitivity>33</microphone_sensitivity>
        <microphone_volume>50</microphone_volume>
      </voicechat>
    </Volume>
  </sound>
  <!--Multiplayer-->
  <multiplayer port="8080">
    <server>US</server>
    <maxping>100</maxping>
  </multiplayer>
  <!--Nastavení profilu-->
  <profile nickname="Player">
    <firtname>Jan</firtname>
    <lastname>Patera</lastname>
    <gender>Male</gender>
    <age>20</age>
    <nationality>American</nationality>
    <email>Franta@sds.cz</email>
  </profile>
  <!--Nastavení ovládání-->
  <controls>
    <input>Mouse and keyboard</input>
    <mouse-sensitivity> 40</mouse-sensitivity>
    <inverted_mouse horizontal="Disabled" vertical="Disabled" />
  </controls>
</settings>
